server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-bold-wave-a12kr8iv-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_VWT3H9thPGgM
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: development